
const HOVER_CODICONS_MIN_VERSION = "1.42";
const HOVER_CODICONS_BROKEN_VERSION = "1.46.0";
const VIEWS_WELCOME_MIN_VERSION = "1.44";

export {
    HOVER_CODICONS_MIN_VERSION,
    HOVER_CODICONS_BROKEN_VERSION,
    VIEWS_WELCOME_MIN_VERSION
};
